version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout
      - run: ./gradlew clean build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
