apiVersion: v1
kind: Service
metadata:
  name: java-template
  labels:
    run: java-template
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    run: java-template

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: java-template
    spec:
      containers:
      - name: java-template
        image: java-template:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://postgres:5432/postgres"