version: '3'
services:

  webapp:
    build: ..
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres:5432/postgres'
    ports:
      - "8080:8080"
    links:
      - "postgres:postgres"

  postgres:
    image: "postgres:latest"
