spring:
  liquibase.change-log: classpath:/db/changelog/changelog-master.xml

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:mem:testdb

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
